/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/login/LoginView': RouteRecordInfo<'/login/LoginView', '/login/LoginView', Record<never, never>, Record<never, never>>,
    '/main': RouteRecordInfo<'/main', '/main', Record<never, never>, Record<never, never>>,
    '/main/': RouteRecordInfo<'/main/', '/main', Record<never, never>, Record<never, never>>,
    '/main/detail/[did]': RouteRecordInfo<'/main/detail/[did]', '/main/detail/:did', { did: ParamValue<true> }, { did: ParamValue<false> }>,
    '/main/header/IndexView': RouteRecordInfo<'/main/header/IndexView', '/main/header/IndexView', Record<never, never>, Record<never, never>>,
    '/main/see/Look01View': RouteRecordInfo<'/main/see/Look01View', '/main/see/Look01View', Record<never, never>, Record<never, never>>,
    '/main/see/Look02View': RouteRecordInfo<'/main/see/Look02View', '/main/see/Look02View', Record<never, never>, Record<never, never>>,
    '/main/see/Look03View': RouteRecordInfo<'/main/see/Look03View', '/main/see/Look03View', Record<never, never>, Record<never, never>>,
    '/main/see/Look04View': RouteRecordInfo<'/main/see/Look04View', '/main/see/Look04View', Record<never, never>, Record<never, never>>,
    '/main/see/Look05View': RouteRecordInfo<'/main/see/Look05View', '/main/see/Look05View', Record<never, never>, Record<never, never>>,
    '/main/see/Look06View': RouteRecordInfo<'/main/see/Look06View', '/main/see/Look06View', Record<never, never>, Record<never, never>>,
    '/main/sidebar/IndexView': RouteRecordInfo<'/main/sidebar/IndexView', '/main/sidebar/IndexView', Record<never, never>, Record<never, never>>,
    '/main/species/[spid]': RouteRecordInfo<'/main/species/[spid]', '/main/species/:spid', { spid: ParamValue<true> }, { spid: ParamValue<false> }>,
    '/main/species/AddBed': RouteRecordInfo<'/main/species/AddBed', '/main/species/AddBed', Record<never, never>, Record<never, never>>,
    '/main/species/distribute/Dialog': RouteRecordInfo<'/main/species/distribute/Dialog', '/main/species/distribute/Dialog', Record<never, never>, Record<never, never>>,
    '/main/species/distribute/LookView': RouteRecordInfo<'/main/species/distribute/LookView', '/main/species/distribute/LookView', Record<never, never>, Record<never, never>>,
    '/see/Look01View': RouteRecordInfo<'/see/Look01View', '/see/Look01View', Record<never, never>, Record<never, never>>,
    '/see/Look02View': RouteRecordInfo<'/see/Look02View', '/see/Look02View', Record<never, never>, Record<never, never>>,
    '/see/Look03View': RouteRecordInfo<'/see/Look03View', '/see/Look03View', Record<never, never>, Record<never, never>>,
    '/see/Look04View': RouteRecordInfo<'/see/Look04View', '/see/Look04View', Record<never, never>, Record<never, never>>,
    '/see/Look05View': RouteRecordInfo<'/see/Look05View', '/see/Look05View', Record<never, never>, Record<never, never>>,
    '/see/Look06View': RouteRecordInfo<'/see/Look06View', '/see/Look06View', Record<never, never>, Record<never, never>>,
    '/see/Look07View': RouteRecordInfo<'/see/Look07View', '/see/Look07View', Record<never, never>, Record<never, never>>,
  }
}
